<a href="https://colab.research.google.com/github/Mtnxy/Datasci/blob/main/28168.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [ ]:
#อ่านข้อมูลจากไฟล์ study.csv
df =pd.read_csv('study.csv')
df.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [ ]:
#ตรวจสอบว่ามีคอลัมอะไรบ้าง
df.columns

Index(['Hours', 'Scores'], dtype='object')

In [ ]:
input_columns =['Hours']#แก้
output_columns =['Scores']#แก้

In [ ]:
X=df.loc[:,input_columns]
y=df.loc[:,output_columns]

In [ ]:
#x.shape

In [ ]:
#splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y ,test_size = .20,random_state =1,)

In [ ]:
#linear Regression
from sklearn.linear_model import LinearRegression
model1 = LinearRegression() #สร้าง model y=mx+b
model1.fit(X_train,y_train) #เรียกskค่า m กับ b

LinearRegression()

In [ ]:
#แสดง m b
print(model1.intercept_)#bจุดตัดแกน y
print(model1.coef_)#mความชัน

[1.18964733]
[[10.12113087]]


In [ ]:
#ทำนายบนชุดทดสอบ
y_p =model1.predict(X_test)

In [ ]:
#วัดผล MSE
from sklearn import metrics
print(np.sqrt(metrics.mean_squared_error(y_test,y_p)))

11380.3421565389


In [ ]:
#หากเรียน 7.5,8.5,9.25
X_quiz = [[7.5],[8.5],[9.25]]
y_quiz = model1.predict(X_quiz)
print(y_quiz)

[[77.09812883]
 [87.21925969]
 [94.81010784]]


In [ ]:
#ใช้ model ที่ได้หากเรียน 12.2 ,15.3 ,1 ,0 ,6 ,7.2
X_quiz =[[12.2],[15.3],[1],[0],[6],[7.2]]
y_quiz =  model1.predict(X_quiz)
print(y_quiz)

[[124.66744389]
 [156.04294958]
 [ 11.3107782 ]
 [  1.18964733]
 [ 61.91643253]
 [ 74.06178957]]


In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [ ]:
#อ่าข้อมูลจากไฟล์
df = pd.read_csv('insurance.csv')
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
#ตรวจคอลัม
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
#กำจัดค่าว่าง
df.dropna(inplace = True)

In [ ]:
input_columns = ['age','bmi','children']
output_columns= ['charges']

In [ ]:
X=df.loc[:,input_columns]
y=df.loc[:,output_columns]

In [ ]:
#splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y ,test_size = .20,random_state =1,)

In [ ]:
#linear Regression
from sklearn.linear_model import LinearRegression
model1 = LinearRegression() #สร้าง model y=mx+b
model1.fit(X_train,y_train) #เรียกskค่า m กับ b

LinearRegression()

In [ ]:
#แสดง m b
print(model1.intercept_)#bจุดตัดแกน y
print(model1.coef_)#mความชัน

[-5889.3730808]
[[246.43462275 300.89595729 254.64158627]]


In [ ]:
#ทำนายบนชุดทดสอบ
y_p =model1.predict(X_test)

In [ ]:
#วัดผล MSE
from sklearn import metrics
print(np.sqrt(metrics.mean_squared_error(y_test,y_p)))

11380.3421565389


In [ ]:
#model ที่ได้ ทำนายเบี้ยประกัน
#age = 30 bmi =35 childen =1
#age = 19 bmi =25 childen =0
#age = 41 bmi =23 childen =2
X_quiz =[[30,35,1],[19,25,0],[41,23,2]]
y_quiz = model1.predict(X_quiz)
print(y_quiz)

[[12289.66569339]
 [ 6315.28368389]
 [11644.33664242]]


In [ ]:
# ตั้งค่า Git
!git config --global user.name "Mtnxy"
!git config --global user.email "kanthita.a@gmail.com"


In [ ]:
!git clone https://github.com/Mtnxy/Datasci.git

Cloning into 'Datasci'...


In [ ]:
!git init
!git add README.md
!git commit -m "first commit"
!git remote add origin https://github.com/Mtnxy/Datasci.git
!git push -u origin main

Reinitialized existing Git repository in /content/.git/
fatal: pathspec 'README.md' did not match any files
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	Datasci/
	sample_data/

nothing added to commit but untracked files present (use "git add" to track)
error: remote origin already exists.
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/Mtnxy/Datasci.git'


In [ ]:
%cd Datasci

/content/Datasci


In [ ]:
# สร้างไฟล์ Python ใหม่
with open("example.py", "w") as f:
    f.write("print('Hello, world!')")
